name: 02 Called Workflow Foo

on:
  workflow_dispatch:
    inputs:
      force_build:
        description: Force Build even if Base image was not updated
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      force_build:
        description: Force Build even if Base image was not updated
        required: false
        default: false
        type: boolean
  # branches:
  #   - '**'  # every branch
  tags:
    - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/ubuntu:latest
          image: library/alpine:latest
      - run: echo Update ${{ steps.check.outputs.needs-updating }}
      - run: echo Input ${{ inputs.force_build }}
      - run: echo Event ${{ github.event_name }}
      - if: ${{ steps.check.outputs.needs-updating || inputs.force_build || (github.event_name == 'push') }}
        run: echo This would be a build process
