name: 02 Called Workflow Foo

on:
  workflow_dispatch:
    inputs:
      greeting:
        description: Greeting
        required: false
        default: 'world'
        type: string
  workflow_call:
    inputs:
      greeting:
        description: Greeting
        required: false
        default: 'world'
        type: string

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, ${{ inputs.greeting }}!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  job1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step1
        run: |
          sleep 10
          echo Done!
      - name: step2
        run: |
          sleep 10
          echo Done!
  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step1
        run: |
          sleep 10
          echo Done!
      - name: step2
        run: |
          sleep 10
          echo Done!
  finish:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: step1
        run: |
          sleep 10
          echo Done!
      - name: step2
        run: |
          sleep 10
          echo Done!
