name: Debug Print

on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows: [Debug Print call]
    types:
      - completed
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJSON(github) }}'
      - run: |
          echo '${{ toJSON(env) }}'
      - run: |
          export
