name: Debug Print

on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows: [Debug Print call]
    types:
      - completed
  push:
  schedule:
    - cron: '23 9 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJSON(github) }}'
      - run: |
          echo '${{ toJSON(env) }}'
      - run: |
          export
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh repo view ${{ github.repository }} --json defaultBranchRef --jq .defaultBranchRef.name
