name: Debug Print

on:
  workflow_dispatch:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJSON(github) }}'
      - run: |
          echo '${{ toJSON(env) }}'
      - run: |
          export
