name: Get Tags JS

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  check-needs-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const response = await github.rest.repos.listTags({
              owner: 'dersimn',
              repo: 'github-action-test'
            });
            const tags = response.data.map(t => t.name);
            return tags;
      - name: Get result
        run: echo '${{steps.set-result.outputs.result}}'
