name: Get Tags JS

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  check-needs-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            // With this Action, require is not possible
            //const semver = require('semver');

            const tags = [];
            for (let i = 0; i < 3; i++) {
              const response = await github.rest.repos.listTags({
                owner: 'dersimn',
                repo: 'github-action-test',
                per_page: 100,
                page: i
              });
              const tags_page = response.data.map(t => t.name);
              console.log(tags_page);

              tags.push(tags_page);
            }
            
            return tags;
      - name: Get result
        run: echo '${{steps.set-result.outputs.result}}'
