name: Get Tags JS

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  check-needs-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            // With this Action, require is not possible
            //const semver = require('semver');

            const tags = [];
            async *listAllTags() {
              let i = 1;
              do {
                console.log(i);
                const response = await github.rest.repos.listTags({
                  owner: 'dersimn',
                  repo: 'github-action-test',
                  per_page: 100,
                  page: i++
                })
                const tags_page = response.data.map(t => t.name);
                console.log(tags_page);
                yield tags_page;
              } while (tags_page.length);
            }
            for await (const tags_page of listAllTags) {
              tags.push(...tags_page);
            }
            
            return tags;
      - name: Get result
        run: echo '${{steps.set-result.outputs.result}}'
