name: Matrix

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  generator:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.gen.outputs.matrix}}
    steps:
      - name: Generate some stuff
        uses: satackey/action-js-inline@v0.0.2
        id: gen
        with:
          script: |
            const core = require('@actions/core');
            core.setOutput('matrix', JSON.stringify([
              'foo',
              'bar'
            ]))
            
      - name: Get result
        run: echo '${{steps.gen.outputs.matrix}}'

  read:
    needs: [ generator ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        array: ${{fromJSON(needs.generator.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.array }}"
