name: Matrix combinations

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  read:
    name: MyName with flavor ${{ matrix.flavor }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        var1: [foo, bar]
        var2: [42, 0815]
        flavor: [alpine, ubuntu]
        include:
          - flavor: alpine
            name: this is alpine
          - flavor: ubuntu
            name: this is ubuntu
            default-flavor: true
    steps:
      - run: |
          echo '${{ toJSON(matrix) }}'
      - run: |
          echo 'true-on-default=${{ matrix.default-flavor || 'false' }}'
      - run: |
          echo 'true-on-default=${{ true && matrix.default-flavor || 'false' }}'
      - run: |
          echo 'always-false=${{ false && matrix.default-flavor }}'
