name: Matrix combinations

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  read:
    needs: [ generator ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        var1: [foo, bar]
        var2: [42, 0815]
        include:
          - flavor: alpine
            name: this is alpine
          - flavor: ubuntu
            name: this is ubuntu
    steps:
      - run: |
          echo '${{ toJSON(matrix) }}'
