name: Run on push to default branch

on:
  push:
    branches:
      - ${{ github.event.repository.default_branch }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
