name: Output secrets/varaibles from settings

on:
  push:
    branches:
      - master
      - main

env:
  BAZ: Baz!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Secret
        run: echo ${{ secrets.FOO_SECRET }}
      - name: Varaible from Settings
        run: echo ${{ vars.BAR_VARIABLE }}
      - name: Environment from Context
        run: echo ${{ env.BAZ }}
      - name: Environment from ENV
        run: echo $BAZ
