name: Run on push to default branch

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Secret
        run: echo ${{ secrets.FOO_SECRET }}
      - name: Varaible from Settings
        run: echo ${{ vars.BAR_VARIABLE }}
