name: Output variable from skipped step

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        if: ${{ (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch') }}
        with:
          base-image: library/alpine:latest
          image: library/alpine:latest

      # if step was skipped output variable is just empty
      - run: echo Update ${{ steps.check.outputs.needs-updating }}
      - run: echo event_name ${{ github.event_name }}

      - name: Decide to continue or skip
        id: should-build
        run: echo continue=${{ (steps.check.outputs.needs-updating == 'true') || (github.event_name != 'schedule') }} >> $GITHUB_OUTPUT

      - run: echo if-step ${{ steps.should-build.outputs.continue }}
      - if: ${{ steps.should-build.outputs.continue == 'true' }}
        run: echo This would be a build process
